name: contact_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  path:
  sqflite:
  firebase_core:
  firebase_auth: ^4.2.0
  google_sign_in: ^5.4.0
  cloud_firestore:
  firebase_storage: ^11.0.16
  image_picker: ^0.8.7+5
  provider: ^6.0.0
  url_launcher: ^6.1.7
  mask_text_input_formatter: ^2.9.0
  flutter_svg: ^2.0.10+1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


  assets:
    - database/contacts.sqlite
    - images/

